version: '3'

services:
  web-server:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      app_net:
        ipv4_address: 10.10.10.2
    extra_hosts:
      - "new_db:10.10.10.3"
      - "dev_db:10.10.10.3"

  database:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      app_net:
        aliases:
          - new_db
          - dev_db
        ipv4_address: 10.10.10.3

networks:
  app_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/28

volumes:
  db_data:
